### ISSUE TITLE
"Speed: 10" not persisting over some early game cutscenes

### ISSUE THREAD

**Issue by Cyan627** [aldelaro5/BugFables-Speedrun-Practice#2]
Hello to everyone who may see this,

The title provides the idea of what's going on here. The double speed sometimes gets canceled out by some cutscenes (or events) in the game. I have provided a short video below of a demonstration of this issue.

[https://youtu.be/0ILoHqTpQwA](url)

Known cutscenes that trigger this issue are:

The Maki tutorial fight
Falling down after grabbing the mushroom in Snakemouth Den
Leif joining your team after freeing them from the web
Leif getting ice
The waterfall after beating the Chapter 1 boss
Statue cutscene with Eetl
Ant Queen after Chapter 1
Starting the festival in Chapter 2

That's about all there is to say on it, thanks for reading.

**Comment by aldelaro5** [comment]
I need to check if the game causes this change naturally, because if that's the case, it would seem very difficult to fix as you would have to reset the speed each time.

**Comment by aldelaro5** [comment]
Fixed by #7
