### ISSUE TITLE
Collision toggle not working as intended

### ISSUE THREAD

**Issue by Cyan627** [aldelaro5/BugFables-Speedrun-Practice#3]
The DEL key function of the 1.1 version of the mod currently does not currently work as intended.  Namely, all collision turns back on as soon as the player jumps. The infinite jump section of the collision toggle stays on, so the effect is not reverted entirely, only partially. A side effect of this is that if you were to trigger a cutscene where the bug you control jumps (termite colosseum/beating ELK), they will not jump in said cutscene. and the player will wait until the game's built-in cutscene failsafe kicks in.

**Comment by aldelaro5** [comment]
Fixed by #8
